version: '3.3'

services:
  db:
    image: postgres:10
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  app:
    build:
      context: services/app
      dockerfile: Dockerfile.development
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec bin/rails s"
    volumes:
      - "~/.bash_history:/.bash_history"
      - "./services/app:/usr/src/app:cached"
      - "/tmp:/tmp:delegated"
    depends_on:
      - db
    env_file:
      - '.env'

  web:
    build:
      context: services/nginx
      dockerfile: Dockerfile
    ports:
     - "8080:80"
    depends_on:
      - app

volumes:
  postgres:
