version: "2"

services:
  db: # if need
    image: postgres
    environment:
      POSTGRES_USER: web
  sut:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: sh -c "bin/setup && bin/rails test"
    environment:
      DATABASE_USERNAME: web
      DATABASE_HOST: db
    depends_on:
      - db
